server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:

  application:
    name: RATING-SERVICE

  config:
    import: optional:configserver:http://localhost:8072
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

okta:
  oauth2:
    issuer: https://dev-01389291.okta.com/oauth2/default
    audience: api://default